import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import Header from "../../components/detail/Header";
import FastSearch from "../../components/index/FastSearch";
import Menubar from "../../components/index/Menubar";
const Map = styled.div`
  width: 100vw;
  height: 100vh;
  background-image: url("/images/IndexMap.png");
`;
const Content = styled.div`
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
`;
const Detail = styled.div`
  position: fixed;
  width: 100vw;
  height: 55vh;
  left: 0;
  bottom: 0;
  background-color: white;
  border-radius: 10px;
  & > .Main {
    display: flex;
    flex-direction: column;
    align-items: center;
    .Placename {
      font-size: 18px;
      font-weight: bold;
      margin-bottom: 5px;
    }
    .Address {
      font-size: 12px;
      margin-bottom: 3px;
    }
    .Buttons {
      display: flex;
    }
    .Start {
      font-size: 12px;
      border: 2px solid #3a96fb;
      border-radius: 15px;
      margin-right: 20px;
      padding: 5px 15px;
      display: flex;
      align-items: center;
    }
    .Arrival {
      font-size: 12px;
      color: white;
      border: 2px solid #3a96fb;
      border-radius: 15px;
      background-color: #3a96fb;
      padding: 5px 15px;
      display: flex;
      align-items: center;
    }
    .icon {
      margin-right: 5px;
    }
  }
`;
export default function Home() {
  return (
    <div>
      <Head>
        <title>WMap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Map></Map>
      <Content>
        <Header />
      </Content>
      <Detail>
        <div className="Main">
          <div className="Placename">구로나눔장애인자립생활센터</div>
          <div className="Address">
            서울 구로구 가마산로 286 SR친오애, 405호
          </div>
          <div className="Buttons">
            <div className="Start">
              <img className="icon" src="/images/icon/Group.png" />
              출발
            </div>
            <div className="Arrival">
              <img className="icon" src="/images/icon/Group.png" />
              도착
            </div>
          </div>
        </div>
      </Detail>
    </div>
  );
}
