import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import Header from "../../components/detail/Header";
import FastSearch from "../../components/index/FastSearch";
import PlaceListWrapper from "../../components/detail/PlaceList";
const Map = styled.div`
  width: 100vw;
  height: 100vh;
  background-color: #ffffff;
`;
const Content1 = styled.div`
  position: fixed;
  top: 0px;
  left: 0;
  width: 100vw;
`;
const Content2 = styled.div`
  position: fixed;
  background-color: #ffffff;
  height: 90%;
  bottom: 0px;
  left: 0;
  width: 100vw;
  overflow: scroll;
  display: flex;
  flex-direction: column;
  align-items: center;
`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>WMap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Map></Map>
      <Content1>
        <Header></Header>
      </Content1>
      <Content2>
        <PlaceListWrapper
          Place="서울특별시청"
          Adrress="서울 중구 세종대로 110 (태평로1가)"
          Call="02-1000-1000"
        ></PlaceListWrapper>
        <PlaceListWrapper
          Place="과천시청"
          Adrress="경기도 과천시"
          Call="02-1000-1000"
        ></PlaceListWrapper>
        <PlaceListWrapper
          Place="광명시청"
          Adrress="경기도 광명시"
        ></PlaceListWrapper>
        <PlaceListWrapper
          Place="부천시청"
          Adrress="경기도 부천시"
          Call="02-1000-1000"
        ></PlaceListWrapper>
        <PlaceListWrapper
          Place="안양시청"
          Adrress="경기도 안양시"
          Call="02-1000-1000"
        ></PlaceListWrapper>
        <PlaceListWrapper
          Place="구리시청"
          Adrress="경기 구리시"
          Call="031-0000-0000"
        ></PlaceListWrapper>
        <PlaceListWrapper
          Place="남양주시청"
          Adrress="경기 남양주시"
          Call="031-1000-1000"
        ></PlaceListWrapper>
        <PlaceListWrapper
          Place="인천시청"
          Adrress="경기 인천시"
          Call="031-1000-1000"
        ></PlaceListWrapper>
      </Content2>
    </div>
  );
}
