import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import FastSearch from "../components/index/FastSearch";
import Menubar from "../components/index/Menubar";
const Map = styled.div`
  width: 100vw;
  height: 100vh;
  background-image: url("/images/IndexMap.png");
`;
export default function Home() {
  return (
    <div>
      <Head>
        <title>WMap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Map></Map>
      <Menubar></Menubar>
      {/* <FastSearch></FastSearch> */}
    </div>
  );
}
