import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import InputBox from "../components/InputBox";

const Navigator = styled.div`
  background-color: #ebf8ff;
  display: flex;
  flex-direction: column;
  padding: 50px;
  .header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    & > .home {
      padding: 10px 20px;
      cursor: pointer;
    }
    & > .nav_right {
      display: flex;
    }
  }
  .login {
    color: #0f3f62;
    display: flex;
    cursor: pointer;
    padding: 10px 20px;
  }
  .membership {
    background-color: white;
    color: blue;
    border-radius: 30px;
    cursor: pointer;
    padding: 10px 20px;
  }
`;
const Line = styled.div`
  background-color: white;
  height: 5px;
  width: 100%;
  margin-bottom: 42px;
`;
const LoginBlock = styled.div`
  background-color: #ebf8ff;
  color: #0f3f62;
  font-size: 14px;
  width: 100%;

  background-color: #ebf8ff;
  display: block;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  display: flex;
  flex-direction: column;
  align-items: center;
  & > button {
    color: white;
    background-color: #4461f2;
    width: 520px;
    height: 50px;
    font-size: 18px;
    border-style: hidden;
    border-radius: 13px;
  }
  .fine {
    display: flex;
    font-weight: bold;
    text-align: center;
    padding: 10px 20px;
    & > a {
      text-decoration: underline;
      cursor: pointer;
    }
  }
  .text {
    text-align: left;
    padding: 10px 20px;
    font-size: 36px;
    margin-bottom: 22px;
  }
  .id,
  .password {
    background-color: #eaf0f7;
    color: #667085;
    text-align: left;
    padding: 10px 20px;
    font-size: 18px;
    width: 520px;
    height: 50px;
    border-radius: 13px;
    border-style: hidden;
    margin-bottom: 9px;
  }
  .id_remember {
    display: flex;
    margin-bottom: 36px;
  }
  .id_text {
    margin-bottom: 8px;
  }
  .fine_text {
    margin-right: 3px;
  }
`;
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigator>
        <div className="header">
          <img className="home" src="/images/logo.png"></img>
          <div className="nav_right">
            <div className="login">로그인</div>
            <div className="membership">회원가입</div>
          </div>
        </div>
      </Navigator>
      <LoginBlock>
        <div className="text">환영합니다. 로그인을 해주세요.</div>
        <Line></Line>
        <div>
          <InputBox text="아이디" placeholder="아이디를 입력하세요" />
          <InputBox text="패스워드" placeholder="패스워드를 입력하세요" />
          <div className="id_remember">
            <input id="remember" type="checkbox"></input>
            <label for="remember">아이디 기억하기</label>
          </div>
        </div>
        <div className="fine">
          <div className="fine_text">아이디나 비밀번호를 잊어버리셨나요?</div>
          <a>아이디, 비밀번호 찾기</a>
        </div>
        <button>로그인</button>
      </LoginBlock>
    </div>
  );
}
