import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import InputBox from "../components/InputBox";
import Nav from "../components/Nav";

const Line = styled.div`
  background-color: white;
  height: 5px;
  width: 100%;
  margin-bottom: 42px;
`;
const LoginBlock = styled.div`
  background-color: #ebf8ff;
  color: #0f3f62;
  font-size: 14px;
  width: 100%;

  background-color: #ebf8ff;
  display: block;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  display: flex;
  flex-direction: column;
  align-items: center;
  & > button {
    color: white;
    background-color: #4461f2;
    width: 240px;
    height: 40px;
    font-size: 12px;
    border-style: hidden;
    border-radius: 10px;
    font-weight: 400;
  }
  .text {
    text-align: left;
    padding: 10px 20px;
    font-size: 20px;
    margin-bottom: 22px;
    font-weight: 600;
  }
  .id_remember {
    display: flex;
    margin-bottom: 30px;
    color: #6b7280;
    & > #box {
      box-sizing: border-box;
      border: 0.7px solid #9fa6b2;
      border-radius: 3px;
      width: 10px;
      height: 10px;
    }
    & > #boxText {
      font-size: 10px;
      display: flex;
      align-items: center;
    }
  }
`;
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav></Nav>
      <LoginBlock>
        <div className="text">환영합니다. 로그인을 해주세요.</div>
        <Line></Line>
        <div>
          <InputBox text="아이디" placeholder="아이디를 입력하세요" />
          <InputBox
            text="비밀번호"
            placeholder="비밀번호를 입력하세요"
            type="password"
          />
          <div className="id_remember">
            <input id="box" type="checkbox"></input>
            <label id="boxText" for="remember">
              아이디 기억하기
            </label>
          </div>
        </div>
        <button>로그인</button>
      </LoginBlock>
    </div>
  );
}
