import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import SearchHeader from "../components/Root/SearchHeader";
import dynamic from "next/dynamic";
import Order from "../components/search/Order";
import StationRoot1 from "../components/Root/StationRoot1";
import StationRoot2 from "../components/Root/StationRoot2";
import StationRoot3 from "../components/Root/StationRoot3";
import Start from "../components/Root/Start";
import Destination from "../components/Root/Destination";
import TimeUnit from "../components/Root/TimeUnit";
import TimeTransfer from "../components/Root/Timetransfer";

const Map = dynamic(() => import("../components/Map"), { ssr: false });

const Content1 = styled.div`
  z-index: 1;
  top: 0;
  left: 0;
  width: 100vw;
`;
const Contente2 = styled.div`
  background-color: white;
  overflow: scroll;
  display: flex;
  flex-direction: column;
`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>WMap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Map></Map> */}

      <Content1>
        <SearchHeader></SearchHeader>
        <Order></Order>
      </Content1>

      <Contente2>
        <TimeTransfer></TimeTransfer>
        <Start></Start>
        <StationRoot1></StationRoot1>
        <StationRoot2></StationRoot2>
        <StationRoot3></StationRoot3>
        <Destination></Destination>
        {/* <Title title={data.name} options={data.option}></Title> */}
      </Contente2>
    </div>
  );
}
// export async function getServerSideProps() {
//   await mongodbconnect();
//   const placeList = await placemodel.find();
//   return { props: { placeList: placeList } };
// }
