import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import ButtonBox from "../components/index/ButtonBox";
import InputBox from "../components/InputBox";
import Nav from "../components/Nav";

const Line = styled.div`
  background-color: white;
  height: 5px;
  width: 100%;
  margin-bottom: 42px;
`;
const SignUpBlock = styled.div`
  background-color: #ebf8ff;
  display: flex;
  flex-direction: column;
  padding: 50px;

  .header {
    display: flex;
    justify-content: space-between;
  }
  .nav {
    display: flex;
  }
  .login {
    display: flex;
    & > div {
      padding: 10px 20px;
    }
  }
  .link {
    padding: 10px 20px;
  }
  .membership {
    background-color: white;
    color: blue;
    border-radius: 30px;
    cursor: pointer;
  }
  .InformationBlock {
    display: flex;
    flex-direction: column;
    background-color: #ebf8ff;
    justify-content: space-between;
    padding: 30px;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    display: flex;
    flex-direction: column;
    align-items: center;
  }
  .Name {
    background-color: #eaf0f7;
  }

  .Id {
    background-color: #eaf0f7;
  }

  .Hi {
    font-size: 24px;
    font-weight: bold;
    margin: 30px;
  }
  .signup_agree {
    display: flex;
    margin-bottom: 30px;
    color: #6b7280;
    & > #box {
      box-sizing: border-box;
      border: 0.7px solid #9fa6b2;
      border-radius: 3px;
      width: 10px;
      height: 10px;
    }
    & > #boxText {
      font-size: 10px;
      display: flex;
      align-items: center;
    }
  }
`;
export default function Home() {
  return (
    <div>
      <Head>
        <title>회원가입</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignUpBlock>
        <Nav></Nav>
        <div className="InformationBlock">
          <div className="Hi">환영합니다. 회원가입을 해주세요.</div>
          <InputBox text="이름" placeholder="이름을 입력하세요" />
          <InputBox text="아이디" placeholder="아이디를 입력하세요" />
          <InputBox text="비밀번호" placeholder="●●●●●●" />
          <InputBox
            text="비밀번호 확인"
            placeholder="비밀번호를 다시 입력하세요"
          />
          <InputBox text="생일" placeholder="생일을 입력하세요" />
          <div className="signup_agree">
            <input id="box" type="checkbox"></input>
            <label id="boxText" for="remember">
              개인정보 수집에 동의합니다.
            </label>
          </div>
          <ButtonBox text="회원가입" />
        </div>
      </SignUpBlock>
    </div>
  );
}
