import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import InputBox from "../components/InputBox";
const SignUpBlock = styled.div`
  background-color: #ebf8ff;
  display: flex;
  flex-direction: column;
  padding: 50px;
  .header {
    display: flex;
    justify-content: space-between;
  }
  .nav {
    display: flex;
  }
  .login {
    display: flex;
    & > div {
      padding: 10px 20px;
    }
  }
  .link {
    padding: 10px 20px;
  }
  .membership {
    background-color: white;
    color: blue;
    border-radius: 30px;
    cursor: pointer;
  }
  .InformationBlock {
    display: flex;
    flex-direction: column;
    background-color: #ebf8ff;
    justify-content: space-between;
    padding: 30px;
    top: 50%;
    left: 50%;
  }
  .Name {
    background-color: #eaf0f7;
  }

  .Id {
    background-color: #eaf0f7;
  }
  .SignupButton {
    background-color: #4461f2;
    font-size: 20px;
    color: #eaf0f7;
    text-align: center;
    width: 250px;
    height: 50px;
    border-radius: 13px;
    border-color: none;
  }
  .Hi {
    font-size: 24px;
    font-weight: bold;
  }
`;
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignUpBlock>
        <div className="header">
          <div className="nav">
            <div className="link">홈</div>
          </div>
          <div className="login">로그인</div>
          <div className="membership">회원가입</div>
        </div>
        <div className="InformationBlock">
          <div className="Hi">환영합니다. 회원가입을 해주세요.</div>
          <div>
            이름 <br></br>
            <input
              className="Name"
              type="text"
              placeholder="이름을 입력하세요"
            ></input>
          </div>
          <InputBox text="아이디" placeholder="아이디를 입력하세요" />
          <InputBox text="비밀번호" placeholder="비밀번호를 입력하세요" />
          <InputBox
            text="비밀번호 확인"
            placeholder="비밀번호를 다시 입력하세요"
          />
          <InputBox text="생일" placeholder="생일을 입력하세요" />
          <div>
            <input type="checkbox"></input> 개인정보 수집에 동의합니다.
            <br></br>
            <button className="SignupButton">회원가입 &#8594; </button>
          </div>
        </div>
        <div>서울특별시 용산구 청파로47길 100(청파동 2가) 숙명여자대학교</div>
      </SignUpBlock>
    </div>
  );
}
