import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import Header from "../../components/detail/Header";
import FastSearch from "../../components/index/FastSearch";
import Title from "../../components/detail/Title";
import Step2 from "../../components/detail/Step2";
import ShareCallBox from "../../components/detail/ShareCall";
import ButtonBox from "../../components/index/ButtonBox";
const Map = styled.div`
  width: 100vw;
  height: 100vh;
  background-image: url("/images/IndexMap.png");
`;
const Content1 = styled.div`
  position: fixed;
  top: 0px;
  left: 0;
  width: 100vw;
`;
const Content2 = styled.div`
  position: fixed;
  background-color: #ebf8ff;
  height: 70vh;
  bottom: 0px;
  left: 0;
  width: 100vw;
  overflow: scroll;
  display: flex;
  flex-direction: column;
  align-items: center;
`;
export default function Home() {
  return (
    <div>
      <Head>
        <title>WMap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Map></Map>
      <Content1>
        <Header></Header>
      </Content1>
      <Content2>
        <Title></Title>
        <ShareCallBox></ShareCallBox>
        <Step2></Step2>
        <ButtonBox text="저장" />
      </Content2>
    </div>
  );
}
